version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=music_db
      - MYSQL_USER=cxp
      - MYSQL_PASSWORD=12345678
#    volumes:
#      - /etc/localtime:/etc/localtime
#      - ./config/mysql:/var/lib/mysql
#      - ./logs/mysql/log:/var/log/mysql
    ports:
      - "3306:3306"


  redis:
    container_name: cache
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=12345678
      - ALLOW_EMPTY_PASSWORD=no
    ports:
      - "6379:6379"
