// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: userService.proto

package pb

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserService service

func NewUserServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserService service

type UserService interface {
	UserLogin(ctx context.Context, in *UserLoginRequest, opts ...client.CallOption) (*UserLoginResponse, error)
	UserRegister(ctx context.Context, in *UserRegisterRequest, opts ...client.CallOption) (*UserRegisterResponse, error)
	CreatePost(ctx context.Context, in *PostCreateRequest, opts ...client.CallOption) (*PostCreateResponse, error)
	GetPostsByAuthor(ctx context.Context, in *GetPostsByAuthorRequest, opts ...client.CallOption) (*GetPostsByAuthorResponse, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) UserLogin(ctx context.Context, in *UserLoginRequest, opts ...client.CallOption) (*UserLoginResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.UserLogin", in)
	out := new(UserLoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UserRegister(ctx context.Context, in *UserRegisterRequest, opts ...client.CallOption) (*UserRegisterResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.UserRegister", in)
	out := new(UserRegisterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) CreatePost(ctx context.Context, in *PostCreateRequest, opts ...client.CallOption) (*PostCreateResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.CreatePost", in)
	out := new(PostCreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetPostsByAuthor(ctx context.Context, in *GetPostsByAuthorRequest, opts ...client.CallOption) (*GetPostsByAuthorResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.GetPostsByAuthor", in)
	out := new(GetPostsByAuthorResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	UserLogin(context.Context, *UserLoginRequest, *UserLoginResponse) error
	UserRegister(context.Context, *UserRegisterRequest, *UserRegisterResponse) error
	CreatePost(context.Context, *PostCreateRequest, *PostCreateResponse) error
	GetPostsByAuthor(context.Context, *GetPostsByAuthorRequest, *GetPostsByAuthorResponse) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		UserLogin(ctx context.Context, in *UserLoginRequest, out *UserLoginResponse) error
		UserRegister(ctx context.Context, in *UserRegisterRequest, out *UserRegisterResponse) error
		CreatePost(ctx context.Context, in *PostCreateRequest, out *PostCreateResponse) error
		GetPostsByAuthor(ctx context.Context, in *GetPostsByAuthorRequest, out *GetPostsByAuthorResponse) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) UserLogin(ctx context.Context, in *UserLoginRequest, out *UserLoginResponse) error {
	return h.UserServiceHandler.UserLogin(ctx, in, out)
}

func (h *userServiceHandler) UserRegister(ctx context.Context, in *UserRegisterRequest, out *UserRegisterResponse) error {
	return h.UserServiceHandler.UserRegister(ctx, in, out)
}

func (h *userServiceHandler) CreatePost(ctx context.Context, in *PostCreateRequest, out *PostCreateResponse) error {
	return h.UserServiceHandler.CreatePost(ctx, in, out)
}

func (h *userServiceHandler) GetPostsByAuthor(ctx context.Context, in *GetPostsByAuthorRequest, out *GetPostsByAuthorResponse) error {
	return h.UserServiceHandler.GetPostsByAuthor(ctx, in, out)
}
