// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0--rc3
// source: songService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSongReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title      string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ArtistAddr string `protobuf:"bytes,2,opt,name=artist_addr,json=artistAddr,proto3" json:"artist_addr,omitempty"`
	Overview   string `protobuf:"bytes,3,opt,name=overview,proto3" json:"overview,omitempty"`
	Content    []byte `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	TokenId    uint64 `protobuf:"varint,5,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
}

func (x *CreateSongReq) Reset() {
	*x = CreateSongReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_songService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSongReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSongReq) ProtoMessage() {}

func (x *CreateSongReq) ProtoReflect() protoreflect.Message {
	mi := &file_songService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSongReq.ProtoReflect.Descriptor instead.
func (*CreateSongReq) Descriptor() ([]byte, []int) {
	return file_songService_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSongReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSongReq) GetArtistAddr() string {
	if x != nil {
		return x.ArtistAddr
	}
	return ""
}

func (x *CreateSongReq) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *CreateSongReq) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *CreateSongReq) GetTokenId() uint64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

type CreateSongRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateSongRes) Reset() {
	*x = CreateSongRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_songService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSongRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSongRes) ProtoMessage() {}

func (x *CreateSongRes) ProtoReflect() protoreflect.Message {
	mi := &file_songService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSongRes.ProtoReflect.Descriptor instead.
func (*CreateSongRes) Descriptor() ([]byte, []int) {
	return file_songService_proto_rawDescGZIP(), []int{1}
}

type FindSongsByAddrReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *FindSongsByAddrReq) Reset() {
	*x = FindSongsByAddrReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_songService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindSongsByAddrReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSongsByAddrReq) ProtoMessage() {}

func (x *FindSongsByAddrReq) ProtoReflect() protoreflect.Message {
	mi := &file_songService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSongsByAddrReq.ProtoReflect.Descriptor instead.
func (*FindSongsByAddrReq) Descriptor() ([]byte, []int) {
	return file_songService_proto_rawDescGZIP(), []int{2}
}

func (x *FindSongsByAddrReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type FindSongsByAddrRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SongInfos []*FindSongsByAddrRes_SongInfo `protobuf:"bytes,1,rep,name=songInfos,proto3" json:"songInfos,omitempty"`
}

func (x *FindSongsByAddrRes) Reset() {
	*x = FindSongsByAddrRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_songService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindSongsByAddrRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSongsByAddrRes) ProtoMessage() {}

func (x *FindSongsByAddrRes) ProtoReflect() protoreflect.Message {
	mi := &file_songService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSongsByAddrRes.ProtoReflect.Descriptor instead.
func (*FindSongsByAddrRes) Descriptor() ([]byte, []int) {
	return file_songService_proto_rawDescGZIP(), []int{3}
}

func (x *FindSongsByAddrRes) GetSongInfos() []*FindSongsByAddrRes_SongInfo {
	if x != nil {
		return x.SongInfos
	}
	return nil
}

type DiscoveryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit uint64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *DiscoveryReq) Reset() {
	*x = DiscoveryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_songService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoveryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryReq) ProtoMessage() {}

func (x *DiscoveryReq) ProtoReflect() protoreflect.Message {
	mi := &file_songService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryReq.ProtoReflect.Descriptor instead.
func (*DiscoveryReq) Descriptor() ([]byte, []int) {
	return file_songService_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoveryReq) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DiscoveryRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SongShortInfos []*DiscoveryRes_SongShortInfo `protobuf:"bytes,1,rep,name=songShortInfos,proto3" json:"songShortInfos,omitempty"`
}

func (x *DiscoveryRes) Reset() {
	*x = DiscoveryRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_songService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoveryRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryRes) ProtoMessage() {}

func (x *DiscoveryRes) ProtoReflect() protoreflect.Message {
	mi := &file_songService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryRes.ProtoReflect.Descriptor instead.
func (*DiscoveryRes) Descriptor() ([]byte, []int) {
	return file_songService_proto_rawDescGZIP(), []int{5}
}

func (x *DiscoveryRes) GetSongShortInfos() []*DiscoveryRes_SongShortInfo {
	if x != nil {
		return x.SongShortInfos
	}
	return nil
}

type DownloadSongReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxId string `protobuf:"bytes,1,opt,name=txId,proto3" json:"txId,omitempty"`
}

func (x *DownloadSongReq) Reset() {
	*x = DownloadSongReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_songService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadSongReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadSongReq) ProtoMessage() {}

func (x *DownloadSongReq) ProtoReflect() protoreflect.Message {
	mi := &file_songService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadSongReq.ProtoReflect.Descriptor instead.
func (*DownloadSongReq) Descriptor() ([]byte, []int) {
	return file_songService_proto_rawDescGZIP(), []int{6}
}

func (x *DownloadSongReq) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type DownloadSongRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SongBytes []byte `protobuf:"bytes,1,opt,name=songBytes,proto3" json:"songBytes,omitempty"`
}

func (x *DownloadSongRes) Reset() {
	*x = DownloadSongRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_songService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadSongRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadSongRes) ProtoMessage() {}

func (x *DownloadSongRes) ProtoReflect() protoreflect.Message {
	mi := &file_songService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadSongRes.ProtoReflect.Descriptor instead.
func (*DownloadSongRes) Descriptor() ([]byte, []int) {
	return file_songService_proto_rawDescGZIP(), []int{7}
}

func (x *DownloadSongRes) GetSongBytes() []byte {
	if x != nil {
		return x.SongBytes
	}
	return nil
}

type FindSongsByAddrRes_SongInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title      string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ArtistAddr string `protobuf:"bytes,3,opt,name=artist_addr,json=artistAddr,proto3" json:"artist_addr,omitempty"`
	Overview   string `protobuf:"bytes,4,opt,name=overview,proto3" json:"overview,omitempty"`
	TokenId    uint64 `protobuf:"varint,5,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	TokenUri   string `protobuf:"bytes,6,opt,name=token_uri,json=tokenUri,proto3" json:"token_uri,omitempty"`
	Amount     uint64 `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Price      uint64 `protobuf:"varint,8,opt,name=price,proto3" json:"price,omitempty"`
	TxId       string `protobuf:"bytes,9,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
}

func (x *FindSongsByAddrRes_SongInfo) Reset() {
	*x = FindSongsByAddrRes_SongInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_songService_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindSongsByAddrRes_SongInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSongsByAddrRes_SongInfo) ProtoMessage() {}

func (x *FindSongsByAddrRes_SongInfo) ProtoReflect() protoreflect.Message {
	mi := &file_songService_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSongsByAddrRes_SongInfo.ProtoReflect.Descriptor instead.
func (*FindSongsByAddrRes_SongInfo) Descriptor() ([]byte, []int) {
	return file_songService_proto_rawDescGZIP(), []int{3, 0}
}

func (x *FindSongsByAddrRes_SongInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FindSongsByAddrRes_SongInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FindSongsByAddrRes_SongInfo) GetArtistAddr() string {
	if x != nil {
		return x.ArtistAddr
	}
	return ""
}

func (x *FindSongsByAddrRes_SongInfo) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *FindSongsByAddrRes_SongInfo) GetTokenId() uint64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *FindSongsByAddrRes_SongInfo) GetTokenUri() string {
	if x != nil {
		return x.TokenUri
	}
	return ""
}

func (x *FindSongsByAddrRes_SongInfo) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *FindSongsByAddrRes_SongInfo) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *FindSongsByAddrRes_SongInfo) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type DiscoveryRes_SongShortInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title      string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ArtistAddr string `protobuf:"bytes,3,opt,name=artist_addr,json=artistAddr,proto3" json:"artist_addr,omitempty"`
	Overview   string `protobuf:"bytes,4,opt,name=overview,proto3" json:"overview,omitempty"`
	TokenId    uint64 `protobuf:"varint,5,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	TokenUri   string `protobuf:"bytes,6,opt,name=token_uri,json=tokenUri,proto3" json:"token_uri,omitempty"`
}

func (x *DiscoveryRes_SongShortInfo) Reset() {
	*x = DiscoveryRes_SongShortInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_songService_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoveryRes_SongShortInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryRes_SongShortInfo) ProtoMessage() {}

func (x *DiscoveryRes_SongShortInfo) ProtoReflect() protoreflect.Message {
	mi := &file_songService_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryRes_SongShortInfo.ProtoReflect.Descriptor instead.
func (*DiscoveryRes_SongShortInfo) Descriptor() ([]byte, []int) {
	return file_songService_proto_rawDescGZIP(), []int{5, 0}
}

func (x *DiscoveryRes_SongShortInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DiscoveryRes_SongShortInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DiscoveryRes_SongShortInfo) GetArtistAddr() string {
	if x != nil {
		return x.ArtistAddr
	}
	return ""
}

func (x *DiscoveryRes_SongShortInfo) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *DiscoveryRes_SongShortInfo) GetTokenId() uint64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *DiscoveryRes_SongShortInfo) GetTokenUri() string {
	if x != nil {
		return x.TokenUri
	}
	return ""
}

var File_songService_proto protoreflect.FileDescriptor

var file_songService_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x6f, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x97, 0x01,
	0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x72, 0x74, 0x69,
	0x73, 0x74, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x76, 0x69,
	0x65, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x76, 0x69,
	0x65, 0x77, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x64,
	0x53, 0x6f, 0x6e, 0x67, 0x73, 0x42, 0x79, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64,
	0x64, 0x72, 0x22, 0xc4, 0x02, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x6f, 0x6e, 0x67, 0x73,
	0x42, 0x79, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x73, 0x12, 0x43, 0x0a, 0x09, 0x73, 0x6f, 0x6e,
	0x67, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x6f, 0x6e, 0x67,
	0x73, 0x42, 0x79, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x73, 0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x09, 0x73, 0x6f, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x1a, 0xe8,
	0x01, 0x0a, 0x08, 0x53, 0x6f, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x41, 0x64,
	0x64, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x12, 0x19,
	0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x55, 0x72, 0x69, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x49, 0x64, 0x22, 0x24, 0x0a, 0x0c, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22,
	0x89, 0x02, 0x0a, 0x0c, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x12, 0x4c, 0x0a, 0x0e, 0x73, 0x6f, 0x6e, 0x67, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x2e, 0x53, 0x6f, 0x6e, 0x67, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e,
	0x73, 0x6f, 0x6e, 0x67, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x1a, 0xaa,
	0x01, 0x0a, 0x0d, 0x53, 0x6f, 0x6e, 0x67, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x76,
	0x69, 0x65, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x76,
	0x69, 0x65, 0x77, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x55, 0x72, 0x69, 0x22, 0x25, 0x0a, 0x0f, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x78, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78,
	0x49, 0x64, 0x22, 0x2f, 0x0a, 0x0f, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x6f,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x6f, 0x6e, 0x67, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x6f, 0x6e, 0x67, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x32, 0x99, 0x02, 0x0a, 0x0b, 0x53, 0x6f, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x0a, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x6f, 0x6e,
	0x67, 0x12, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x12, 0x47, 0x0a, 0x09, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x6f, 0x6e, 0x67, 0x73,
	0x12, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x46, 0x69, 0x6e, 0x64,
	0x53, 0x6f, 0x6e, 0x67, 0x73, 0x42, 0x79, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1c,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x6f,
	0x6e, 0x67, 0x73, 0x42, 0x79, 0x41, 0x64, 0x64, 0x72, 0x52, 0x65, 0x73, 0x12, 0x44, 0x0a, 0x0c,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x6f, 0x6e, 0x67, 0x12, 0x19, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x53, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x6f, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x12, 0x3b, 0x0a, 0x09, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x12,
	0x16, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x42,
	0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_songService_proto_rawDescOnce sync.Once
	file_songService_proto_rawDescData = file_songService_proto_rawDesc
)

func file_songService_proto_rawDescGZIP() []byte {
	file_songService_proto_rawDescOnce.Do(func() {
		file_songService_proto_rawDescData = protoimpl.X.CompressGZIP(file_songService_proto_rawDescData)
	})
	return file_songService_proto_rawDescData
}

var file_songService_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_songService_proto_goTypes = []interface{}{
	(*CreateSongReq)(nil),               // 0: services.CreateSongReq
	(*CreateSongRes)(nil),               // 1: services.CreateSongRes
	(*FindSongsByAddrReq)(nil),          // 2: services.FindSongsByAddrReq
	(*FindSongsByAddrRes)(nil),          // 3: services.FindSongsByAddrRes
	(*DiscoveryReq)(nil),                // 4: services.DiscoveryReq
	(*DiscoveryRes)(nil),                // 5: services.DiscoveryRes
	(*DownloadSongReq)(nil),             // 6: services.DownloadSongReq
	(*DownloadSongRes)(nil),             // 7: services.DownloadSongRes
	(*FindSongsByAddrRes_SongInfo)(nil), // 8: services.FindSongsByAddrRes.SongInfo
	(*DiscoveryRes_SongShortInfo)(nil),  // 9: services.DiscoveryRes.SongShortInfo
}
var file_songService_proto_depIdxs = []int32{
	8, // 0: services.FindSongsByAddrRes.songInfos:type_name -> services.FindSongsByAddrRes.SongInfo
	9, // 1: services.DiscoveryRes.songShortInfos:type_name -> services.DiscoveryRes.SongShortInfo
	0, // 2: services.SongService.UploadSong:input_type -> services.CreateSongReq
	2, // 3: services.SongService.FindSongs:input_type -> services.FindSongsByAddrReq
	6, // 4: services.SongService.DownloadSong:input_type -> services.DownloadSongReq
	4, // 5: services.SongService.Discovery:input_type -> services.DiscoveryReq
	1, // 6: services.SongService.UploadSong:output_type -> services.CreateSongRes
	3, // 7: services.SongService.FindSongs:output_type -> services.FindSongsByAddrRes
	7, // 8: services.SongService.DownloadSong:output_type -> services.DownloadSongRes
	5, // 9: services.SongService.Discovery:output_type -> services.DiscoveryRes
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_songService_proto_init() }
func file_songService_proto_init() {
	if File_songService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_songService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSongReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_songService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSongRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_songService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindSongsByAddrReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_songService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindSongsByAddrRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_songService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoveryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_songService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoveryRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_songService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadSongReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_songService_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadSongRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_songService_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindSongsByAddrRes_SongInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_songService_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoveryRes_SongShortInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_songService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_songService_proto_goTypes,
		DependencyIndexes: file_songService_proto_depIdxs,
		MessageInfos:      file_songService_proto_msgTypes,
	}.Build()
	File_songService_proto = out.File
	file_songService_proto_rawDesc = nil
	file_songService_proto_goTypes = nil
	file_songService_proto_depIdxs = nil
}
