// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: songService.proto

package pb

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for SongService service

func NewSongServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for SongService service

type SongService interface {
	UploadSong(ctx context.Context, in *CreateSongReq, opts ...client.CallOption) (*CreateSongRes, error)
	FindSongs(ctx context.Context, in *FindSongsByAddrReq, opts ...client.CallOption) (*FindSongsByAddrRes, error)
	DownloadSong(ctx context.Context, in *DownloadSongReq, opts ...client.CallOption) (*DownloadSongRes, error)
	Discovery(ctx context.Context, in *DiscoveryReq, opts ...client.CallOption) (*DiscoveryRes, error)
}

type songService struct {
	c    client.Client
	name string
}

func NewSongService(name string, c client.Client) SongService {
	return &songService{
		c:    c,
		name: name,
	}
}

func (c *songService) UploadSong(ctx context.Context, in *CreateSongReq, opts ...client.CallOption) (*CreateSongRes, error) {
	req := c.c.NewRequest(c.name, "SongService.UploadSong", in)
	out := new(CreateSongRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *songService) FindSongs(ctx context.Context, in *FindSongsByAddrReq, opts ...client.CallOption) (*FindSongsByAddrRes, error) {
	req := c.c.NewRequest(c.name, "SongService.FindSongs", in)
	out := new(FindSongsByAddrRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *songService) DownloadSong(ctx context.Context, in *DownloadSongReq, opts ...client.CallOption) (*DownloadSongRes, error) {
	req := c.c.NewRequest(c.name, "SongService.DownloadSong", in)
	out := new(DownloadSongRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *songService) Discovery(ctx context.Context, in *DiscoveryReq, opts ...client.CallOption) (*DiscoveryRes, error) {
	req := c.c.NewRequest(c.name, "SongService.Discovery", in)
	out := new(DiscoveryRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SongService service

type SongServiceHandler interface {
	UploadSong(context.Context, *CreateSongReq, *CreateSongRes) error
	FindSongs(context.Context, *FindSongsByAddrReq, *FindSongsByAddrRes) error
	DownloadSong(context.Context, *DownloadSongReq, *DownloadSongRes) error
	Discovery(context.Context, *DiscoveryReq, *DiscoveryRes) error
}

func RegisterSongServiceHandler(s server.Server, hdlr SongServiceHandler, opts ...server.HandlerOption) error {
	type songService interface {
		UploadSong(ctx context.Context, in *CreateSongReq, out *CreateSongRes) error
		FindSongs(ctx context.Context, in *FindSongsByAddrReq, out *FindSongsByAddrRes) error
		DownloadSong(ctx context.Context, in *DownloadSongReq, out *DownloadSongRes) error
		Discovery(ctx context.Context, in *DiscoveryReq, out *DiscoveryRes) error
	}
	type SongService struct {
		songService
	}
	h := &songServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&SongService{h}, opts...))
}

type songServiceHandler struct {
	SongServiceHandler
}

func (h *songServiceHandler) UploadSong(ctx context.Context, in *CreateSongReq, out *CreateSongRes) error {
	return h.SongServiceHandler.UploadSong(ctx, in, out)
}

func (h *songServiceHandler) FindSongs(ctx context.Context, in *FindSongsByAddrReq, out *FindSongsByAddrRes) error {
	return h.SongServiceHandler.FindSongs(ctx, in, out)
}

func (h *songServiceHandler) DownloadSong(ctx context.Context, in *DownloadSongReq, out *DownloadSongRes) error {
	return h.SongServiceHandler.DownloadSong(ctx, in, out)
}

func (h *songServiceHandler) Discovery(ctx context.Context, in *DiscoveryReq, out *DiscoveryRes) error {
	return h.SongServiceHandler.Discovery(ctx, in, out)
}
